version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
       - "8082:3306"
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "127.0.0.1:80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./:/var/www/html
volumes:
    db_data: